### PR TITLE
Add IPython as nicer Python environment

### PR DESCRIPTION
**Pull request by MakisH**
@carlosal1015 suggested that we also add [Jupyter](https://ipython.org/) (just the command line, not the full Notebooks environment) to get suggestions when writing Python code.

@BenjaminRodenberg or @IshaanDesai approve if you think this is a good idea. If you want to recommend more Python-related tools that would be useful in the VM (but not very large to install), this would be great!

### CODE REVIEW

**Comment by IshaanDesai** [comment]
I don't really understand which suggestions are included when we install `ipython`. I have very little experience with IPython so would like to have some context here.

**Comment by uekerman** [comment]
I guess, some solution would be great where we have some interaction with the docstrings of pyprecice. Automatic code completion, ...

**Comment by carlosal1015** [comment]
Thanks for opening this topic about [`ipython3`](https://packages.ubuntu.com/focal/ipython3), while we working in the early days with python bindings, I noticed people (me too) that using `pyprecice` for the first time, we took us a little extra time read the documentation (maybe this program could save user's time). If in the future there is a page generated by sphinx to view the pyprecice docs, `ipython` could be omitted in the virtual machine.

In addition to those shown in [this video](https://0x0.st/oKCL.mp4) or [short demo](https://asciinema.org/a/472785), there are more additional features [shown there](https://ipython.readthedocs.io/en/stable/#ipython-documentation), maybe not necessary in a workshop.

Optionally, could include an a script in non-interactive mode that provides `ipython` (needs to be tested if it doesn't break other existing modules) like for `install_vscode.sh` in the future.

P.S.: I'll fix the `pyprecice` version numbering ASAP.

**Review by IshaanDesai — APPROVED** [review]
I tried out `ipython` on the command line and the suggestions are indeed very helpful! Lets add this to the vm :+1:

**Pull request merged**
