### PR TITLE
Manually uninstall fenics-ufl package to avoid FEniCS not working

### PR DESCRIPTION
**Pull request by IshaanDesai**
Fixes error which popped up in https://github.com/precice/vm/pull/50#issuecomment-1322840394

### CODE REVIEW

**Comment by IshaanDesai** [comment]
@MakisH I am not sure if the `install-fenics.sh` script is the right place to manually uninstall `fenics-ufl` (to avoid the problem), but we can try this. I looked through the Vagrantfile to see which packages are installed after the fenics-adapter and it seems highly unlikely that fenics-ufl will be installed somehow later.

**Comment by MakisH** [comment]
I already had that before and removed it in https://github.com/precice/vm/pull/22, based on the discussion of https://github.com/precice/vm/issues/4.

Did you check if this solution works in the VM?

**Comment by IshaanDesai** [comment]
> Did you check if this solution works in the VM?

Yes I checked my downloading the box from the latest passed test on the develop branch and the solution of manually uninstalling `fenics-ufl` works. It was only after I confirmed this did I open this PR.

**Comment by IshaanDesai** [comment]
Can we build the box for this branch? Then I can check if the solution works when done via the provisioning script.

**Pull request merged**
